# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bk56UHkY8eHiK9QccOQ5gFx_-r_q_qo
"""

import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle, Polygon

fig, ax = plt.subplots(figsize=(6, 8))

# --- GŁOWA ---
ax.add_patch(Circle((0.5, 0.78), 0.15, color="#f2d6b3"))

# --- CZAPKA ---
ax.add_patch(Polygon([[0.35, 0.88], [0.65, 0.88], [0.5, 1.02]], color="red"))
ax.add_patch(Rectangle((0.32, 0.85), 0.36, 0.05, color="white"))
ax.add_patch(Circle((0.5, 1.02), 0.05, color="white"))

# --- TWARZ ---
ax.add_patch(Circle((0.45, 0.81), 0.02, color="black"))
ax.add_patch(Circle((0.55, 0.81), 0.02, color="black"))
ax.add_patch(Circle((0.5, 0.76), 0.03, color="red"))

# --- BRODA ---
ax.add_patch(Polygon([[0.38, 0.74], [0.62, 0.74], [0.75, 0.50], [0.25, 0.50]], color="white"))

# --- KOSZULKA (bez dolnego prostokąta!) ---
ax.add_patch(Circle((0.50, 0.33), 0.21, color="red"))

# --- DŁUGIE RĄCZKI ---
ax.add_patch(Rectangle((0.62, 0.45), 0.14, 0.18, color="red"))   # prawe ramię
ax.add_patch(Circle((0.76, 0.45), 0.05, color="#f2d6b3"))        # prawa dłoń
ax.add_patch(Rectangle((0.24, 0.45), 0.14, 0.18, color="red"))   # lewe ramię
ax.add_patch(Circle((0.24, 0.45), 0.05, color="#f2d6b3"))        # lewa dłoń

# --- OKRĄGŁY WOREK ---
ax.add_patch(Circle((0.85, 0.18), 0.14, color="#8b4513"))
ax.add_patch(Circle((0.90, 0.28), 0.03, color="yellow"))

# --- NOGI ---
ax.add_patch(Rectangle((0.40, 0.05), 0.08, 0.13, color="red"))
ax.add_patch(Rectangle((0.52, 0.05), 0.08, 0.13, color="red"))

# --- BUTY ---
ax.add_patch(Rectangle((0.36, 0.00), 0.16, 0.06, color="black"))
ax.add_patch(Rectangle((0.48, 0.00), 0.16, 0.06, color="black"))

# --- PREZENTY ---
# prezent 1
ax.add_patch(Rectangle((0.10, 0.05), 0.10, 0.10, color="#ff4444"))
ax.add_patch(Rectangle((0.145, 0.05), 0.02, 0.10, color="yellow"))
ax.add_patch(Rectangle((0.10, 0.095), 0.10, 0.02, color="yellow"))

# prezent 2
ax.add_patch(Rectangle((0.22, 0.05), 0.12, 0.12, color="#44aaff"))
ax.add_patch(Rectangle((0.265, 0.05), 0.02, 0.12, color="white"))
ax.add_patch(Rectangle((0.22, 0.10), 0.12, 0.02, color="white"))

# prezent 3
ax.add_patch(Rectangle((0.10, 0.18), 0.14, 0.14, color="#33cc33"))
ax.add_patch(Rectangle((0.163, 0.18), 0.02, 0.14, color="red"))
ax.add_patch(Rectangle((0.10, 0.245), 0.14, 0.02, color="red"))

# --- USTAWIENIA ---
ax.set_xlim(0, 1)
ax.set_ylim(0, 1.15)
ax.axis('off')

# --- Streamlit ---
st.pyplot(fig)